### ISSUE TITLE
Issue: Proxy not detected

### ISSUE THREAD

**Issue by caniko** [nektos/act#1032]
## System information
- Operating System: Linux
- Architecture: x64 (64-bit)
- Docker version: 20.10.12
- `act` version: 0.2.25

## Expected behaviour

```shell
[Release to PyPI/deploy]   ❗  ::error::connect ECONNREFUSED 140.82.121.5:443
[Release to PyPI/deploy]   ❌  Failure - Set up Python 3.8
Error: exit with `FAILURE`: 1
```

## Actual behaviour

Proxy should be detected from my environment variables in `/etc/environemnt`.

**FYI**
I don't have this issue when I run `docker` and/or `minikube`, but `docker-compose`.

## Steps to reproduce

Run `act` behind proxy

**Comment by KnisterPeter** [comment]
@caniko I don't think it's a bug but more a missing feature. Thanks for reporting.

**Comment by caniko** [comment]
Please get your definitions right. It is a [bug](https://en.wikipedia.org/wiki/Software_bug).

**Comment by catthehacker** [comment]
Hi, it is not a bug. For it to be a bug, we would have to consider local environment (where `act` is executed), which we do not, and as you might think it is undesired behaviour, it's not that, simply because we never supported proxies.
A bug is a flaw in code, a mistake made by the one who have written the source code (according to your definition) but there never was a mistake of not adding proxy support.

You can currently pass `HTTP_PROXY`/`HTTPS_PROXY` via `--env`/`--env-file` if needed as a workaround.

**Comment by caniko** [comment]
Try to make a product sell it, and use the same logic.

Furthermore, the workaround changes the entire narrative. Thank you.

**Comment by KnisterPeter** [comment]
Unbelievable. This is free software.
Implement and contribute if you need it!

**Comment by caniko** [comment]
We are having an argument over semantics, and not the merits of free software.

**Comment by caniko** [comment]
> Furthermore, the workaround changes the entire narrative. Thank you.

Did you read my last message before closing the issue? I implied that the `--env` the method is fine.

**Comment by KnisterPeter** [comment]
Just to make this even more obvious: you closed the issue :wink:

**Comment by helozjisky** [comment]
Put this in ~/.actrc should work correctly
--env http_proxy=http://{ip:port}
--env https_proxy=http://{ip:port}
