### ISSUE TITLE
file path with spaces not supported. (bash: /mnt/d/java: No such file or directory)

### ISSUE THREAD

**Issue by sijmenvb** [nektos/act#1046]
i keep getting the following error `bash: /mnt/d/java: No such file or directory`

the issue seems to be the the command is `docker exec cmd=[bash --noprofile --norc -e -o pipefail /mnt/d/java projects/Software Engenering/workflow/2] user=`
but it seems to split on the space.

## Expected behaviour
I would expect the commands to have quotes for the path like so : `docker exec cmd=[bash --noprofile --norc -e -o pipefail "/mnt/d/java projects/Software Engenering/workflow/2"] user=`
or some replacing spaces with _ (underscores) 

## Actual behaviour

it does not and sees the path as only /mnt/d/java

**Comment by robertkowalski** [comment]
it works for me, can you provide a testcase / repository to reproduce the issue? it would be good if you could fill out the issue template, so we can reproduce the environment, too

**Comment by ChristopherHX** [comment]
This specfic issue has been fixed in https://github.com/nektos/act/releases/tag/v0.2.26.
By creating the script files in a container directory without spaces.

Could still cause problems if act starts supporting non container scenarios. Seems like we have a lack of test cases about the `shell` option of act, the action/runner might have similar problems.
