### ISSUE TITLE
Enhancement: Breakpoints

### ISSUE THREAD

**Issue by ben-albrecht** [nektos/act#1050]
## Describe feature

I am not sure if this falls within the scope of the project, is already possible through other means, or is not feasible, but I wanted to capture the general sentiment in a feature request:

It would be really useful to have a way to connect to a workflow  with an interactive shell at a designated breakpoint for debugging purposes. For example, a workflow fails at step `N`, so I set a breakpoint at step `N-1`, and run `act` which will follow the workflow until reaching step `N-1` and then drop me into an interactive shell at that step.

**Comment by lejtemxviw** [comment]
If I understood how act works right (:-p), it starts a container when it tries to run your workflow, and it leaves the container up when executions encounters an error.  However, I think it does run the clean up steps on workflow exit.  Would it be enough for this if there was an option that got act to just quit on encountering an error, without running the cleanup steps, and still leaving the container up?  Or pause with a "Hit enter to continue...." prompt, so that one can ssh into the still-running container separately, then come back and hit enter to let it finish running the cleanup steps?

**Comment by ben-albrecht** [comment]
I am not familiar enough with act to know what the cleanup steps are doing, but that sounds like a possible way to approach this. Being able to access the container and any artifacts left behind after the error happened would be helpful.

**Comment by ben-albrecht** [comment]
>That's already the default behaviour

Oh cool, I suspected this might already be possible. @catthehacker (or anyone else) -- would you mind giving a basic example of how one would do this or point me to an example doc? 

We can probably close the issue with that information provided here, in case anyone else stumbles across this issue looking for the same feature.

**Comment by dheerajbhaskar** [comment]
I found this after a lot of trial and error:

## How to stop the workflow at a particular step (especially when it's not failing. For say REPL style development of workflow)
1. Comment out all the steps after the one you want to stop at. If want to stop at "step 3", comment out all the steps after the said "step 3"
2. Run act with reuse option `act -r`.
3. DONE. Act performed the steps, left the container running for you to inspect. Get a shell into the container and do your thing `docker exec -it <container> /bin/bash`

NOTE: Remember that with the `-r` option, act re-uses the container. Github does not re-use containers. So, be sure to test your workflows without the `-r` option.

**Comment by aradar46** [comment]
late to this, but since it still comes up in search:mybe try this https://github.com/aradar46/fermata that does what the original post describes, on top of act. Disclosure: it's my project, and Claude wrote a good chunk of it. It vendors act with a ~200 line patch and adds breakpoints:

`fermata run -W .github/workflows/ci.yml --break "step name"`

It runs until that step, pauses with the container alive, and gives you a prompt. shell is the docker exec from above without hunting for the container id, env shows the step's environment, continue runs the rest of the job, no commenting out steps and restoring them after. It also pauses automatically when a step fails, and retry reruns just that step, so a fix doesn't cost you the whole setup again.

The execution itself is all act's code, Fermata only adds the pause layer.
