### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by francisfuzz** [nektos/act#17]
👋 Hey @cplee and @nektos team!

Opening this issue to ask: any plans to introduce automated testing for this project (through a GitHub Action or a third-party CI service)?

**Comment by cplee** [comment]
@francisfuzz awesome idea.  Step 1...can you get the @nektos organization added to the GitHub Actions beta so I can add some automated test actions?

**Comment by francisfuzz** [comment]
@cplee - Hi! Our team recently enabled the @nektos organization for beta. 🚀

**Comment by cplee** [comment]
Aweseome, @francisfuzz!  I have it setup now so that the unit tests and static analysis is being done via a GitHub Action.  I also had added a unit test to cover #12 (see below) and plan to continue adding unit tests as issues are opened.  

Do you have any other thoughts on additional approaches to automated testing?

https://github.com/nektos/act/blob/master/actions/parser_test.go#L51-L59

**Comment by francisfuzz** [comment]
Also, I'd like to leave this note here for posterity (aka future me) so I don't forget!

* Checked [commit history](https://github.com/nektos/act/commits/master)
* https://github.com/nektos/act/commit/320e9b60576739f791e301b47517d5b064f0b3d5 has a clickable checkmark that exposes the check runs created for it
* Passing check run are visible here:
  * https://github.com/nektos/act/runs/53874274
  * https://github.com/nektos/act/runs/53874303
