### ISSUE TITLE
Doesn't copy symlinks 

### ISSUE THREAD

**Issue by pascalwhoop** [nektos/act#209]
We're using symlinks in our git repo to keep our terraform code DRY. Doesn't really matter to act, but generally, if GIT supports symlinks, so should act

```
[Apply Terraform/apply terraform] Unable to copy link providers.tf --> ../_universal/providers.tf
[Apply Terraform/apply terraform] Unable to copy link universal.auto.tfvars --> ../_universal/universal.auto.tfvars
[Apply Terraform/apply terraform] Unable to copy link providers.tf --> ../_universal/providers.tf
[Apply Terraform/apply terraform] Unable to copy link universal.auto.tfvars --> ../_universal/universal.auto.tfvars
[Apply Terraform/apply terraform] Unable to copy link providers.tf --> ../_universal/providers.tf
[Apply Terraform/apply terraform] Unable to copy link universal.auto.tfvars --> ../_universal/universal.auto.tfvars
```

**Comment by nilsdebruin** [comment]
Hi, I can confirm that this is broken in version 0.2.8, when I downgraded to 0.2.7 it works as expected (MacOSX Catalina, installed via HomeBrew)

**Comment by cplee** [comment]
Likely related to https://github.com/nektos/act/commit/8c290994c1b84153d2b9f911ac3bb64858fb5e35

**Comment by lyleunderwood** [comment]
Why was [this](https://github.com/nektos/act/commit/c44b71c9962f527e9c8847a7a3b959c71ac41b21) necessary? Was there an issue associated with this?

**Comment by Nilegfx** [comment]
any updates regarding this?

**Comment by lyleunderwood** [comment]
@cplee does the above look familiar to you?

**Comment by cplee** [comment]
@lyleunderwood - this was for #182

**Comment by lyleunderwood** [comment]
Oh, hm. It looks like the output referenced in the original issue is describing the fact that the _contents_ of a symlink are not copied to the tar archive, because a symlink doesn't really have contents. The file headers for the symlinks are still written to the archive, which I believe should be enough for them to be untar'd correctly. It seems like the real question here is, do symlinks _actually_ not show up alongside the other copied files? It seems like they should, in which case the warning should probably be squelched.

https://github.com/nektos/act/blob/729adec5e52eb8bf83fb3ea1cc0d1b510350e09e/pkg/container/docker_run.go#L386-L410
