### ISSUE TITLE
Supply secrets with a .env file

### ISSUE THREAD

**Issue by Djiit** [nektos/act#58]
It would be great to be able to provide some sort of `.env` file to avoid prompting user each time you run a workflow.

**Comment by Haegin** [comment]
If the secret vars are in the current environment it seems that `act` uses them automatically. I moved from using `.env` files to using `direnv` a while back as that loads environment vars into the environment automatically when you `cd` into a directory and unloads them when you leave. Because the env vars are in the environment tools then don't need to support a `.env` file, they just need to support reading environment vars which every language I've used can do natively.

**Comment by maxheld83** [comment]
I've documented this in a PR: https://github.com/nektos/act/pull/66

**Comment by cplee** [comment]
Support is now available to provide default vals via [.actrc](https://github.com/nektos/act#configuration)
