### ISSUE TITLE
Enhancement: Summarize Job Results and Separate Job Outputs

### ISSUE THREAD

**Issue by adamsmd** [nektos/act#941]
Is there some way to summarize job results and separate job outputs (or some other project that builds on this one to add that)?  For example, like how GitHub shows particular runs of a workflow.

I have some jobs with large matrices, and it would be helpful to have something that makes it easier to track which entries failed and trace the failure causes.

**Comment by pwoolvett** [comment]
My grain of sand: `alias act='act | tee >(grep -P "\x{2705}|\x{274c}|\x{2b50}|\x{1F9EA}|\x{1F680}" >summary.log) act.log'`

Explanation and usage (bash):

0. use named jobs and include matrix data in the name, eg:

    ```yaml
    jobs:
      default:
        name: "${{ matrix.env }}-${{ matrix.os }})"
    ````
1. instead of `act`, run `act | tee >(grep -P "\x{2705}|\x{274c}|\x{2b50}|\x{1F9EA}|\x{1F680}" >summary.log) act.log`
    * This filters out all code not containing the emojis by their unicode, eg  ✅ (=2705) for success,  ❌ (=274C) for failures, etc
    * `act.log` contains copy of the terminal output
    * `summary.log` contains the filtered version. You can add or remove emojis to the grep to have more or less info, eg keep only ❌ if you want to look at failed ones: `act | tee >(grep -P "\x{274c}" >summary.log) act.log`

2. let act run
3. Look at `summary.log` and copy a job's name which requires attention. It has the format :`<pipeline name>/<job name>`
4. Do something

    4.1 Job summary: `cat act.log | fgrep "<job name>" | grep -P "\x{2705}|\x{274c}|\x{2b50}|\x{1F9EA}|\x{1F680}"`
    4.2 Job output after error only,  `cat act.log | fgrep "<job name>" | fgrep -A $(cat act.log | wc -l) "$(cat act.log | fgrep "<job name>" | grep -P "\x{2b50}" | tail -1)"`
    4.3 Full output: `cat act.log | fgrep "<job name>"`

I've got these aliased and as functions in `bashrc`
My only problem so far is the `summary` get populated when act finishes...
